### ISSUE TITLE
You uploaded the wrong file on e

### ISSUE THREAD

**Issue by alishachris** [Spuds/Elk-Solved-Topics#1]

**Comment by alishachris** [comment]
Please check elkarte forum. YOu uploaded the solved topic file instead.

**Comment by Spuds** [comment]
I'm not quite understanding where the wrong file is located.  Could you please provide more details?

**Comment by alishachris** [comment]
Hello

here is the link.

http://addons.elkarte.net/2014/09/Social-Links/

**Comment by Spuds** [comment]
I see .. will check the social links addon.  Can't do anything untill this pm

**Comment by Spuds** [comment]
I fixed the link in the social links addon so it points to the correct archive.

**Comment by alishachris** [comment]
Thanks spud.
